### ISSUE TITLE
Design & Components

### ISSUE THREAD

**Issue by pedrolucasp** [authenticvision/digitalsoul#15]
We could maybe introduce the usage of some building blocks from the tailwind community:

- [daisyUI](https://daisyui.com)
- https://github.com/shadcn-ui/ui
- https://github.com/tailwindlabs/headlessui
- https://github.com/mdbootstrap/Tailwind-Elements
- https://github.com/ben-rogerson/twin.macro

Since the app will be a bit small, we could also just build the necessary blocks we'll use anyway.

**Comment by tbergmueller** [comment]
Attached @Theisflo draft
[ds_ui.pdf](https://github.com/authenticvision/digitalsoul/files/13114509/ds_ui.pdf)

Note NFT-Data shall be uploaded to `/srv/app/nftdata` (e.g. an image). Details on the binary-data management (db-schema, flow, ... ) will be outlined in #25

**Comment by tbergmueller** [comment]
Assign to @pedrolucasp to implement in branch `new-ui`

**Comment by tbergmueller** [comment]
Closing, since many break-out tasks exist
