### ISSUE TITLE
Customizable Landing Page

### ISSUE THREAD

**Issue by tbergmueller** [authenticvision/digitalsoul#82]
The landing page shall have customization options per collection, at least:
- Colors
- Logo

Optionally:
- Choice of auto-claim or claim-button per Collection
- Free-form HTML content
- Building blocks

**Comment by pedrolucasp** [comment]
On Wed, May 01, 2024 at 11:40:28PM -0700, Thomas Bergmueller wrote:
> The landing page shall have customization options per collection, at least:
> - Colors
> - Logo
> 
> Optionally:
> - Choice of auto-claim or claim-button per Collection
> - Free-form HTML content
> - Building blocks

So we might want to add a sort of Admin panel to DigitalSoul, where the
user can customize the landing page (and other settings) for the
instance? This would be a great feature to have, as it would allow the
user to have a more personalized experience with the platform etc.

**Comment by tbergmueller** [comment]
In https://github.com/authenticvision/digitalsoul/pull/83, implemented the following:

- Colors based on DaisyUI-Theme generator
- Logo
- Auto-Claim or Claim-Button

Not done:
- Free-Form HTML content
- Building blocks.

> So we might want to add a sort of Admin panel to DigitalSoul, where the
user can customize the landing page (and other settings) for the
instance?

The customization of the landing page (now called the "collection" / "collection-item"-page) is done per collection, as there are multiple different collections per instance. 

For simplicity (and while functionality is very rudimental), I added it to the contract-settings. Later (when we do building-blocks and allow adding collection owners to add their own HTML / DOM-style blocks), this most certainly needs to become a separate page.

**Comment by tbergmueller** [comment]
#83 was reviewed internally and functionality also checked by selected customers. 
@pedrolucasp the key component to customizable theme feels a bit hacky, as it sets the Daisy-Colors / variables directly in the document's style element, see [here](https://github.com/authenticvision/digitalsoul/pull/83/files#diff-e8ffe2a4d916f7217182516ce7dbda1f3f8694657bb5dfe27f8a1e2dd63c1845R297). 

In case you know a better way, please let me know :)
